# Generated by Django 2.2 on 2019-05-02 07:59

import common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[(common.enums.TestEnum('Red'), 'Red'), (common.enums.TestEnum('Yellow'), 'Yellow'), (common.enums.TestEnum('Green'), 'Green')], max_length=2)),
            ],
        ),
    ]
