# Generated by Django 2.2 on 2019-05-02 08:04

import common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='color',
            field=models.CharField(choices=[(common.enums.TestEnum('Red'), 'Red'), (common.enums.TestEnum('Yellow'), 'Yellow'), (common.enums.TestEnum('Green'), 'Green')], max_length=10),
        ),
    ]
