# Generated by Django 2.2 on 2019-05-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190502_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('Y', 'Yellow'), ('G', 'Green')], max_length=10),
        ),
    ]
