# Generated by Django 2.2 on 2019-04-26 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('furnitures', '0006_delete_review'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileUser')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnitures.Furniture')),
            ],
        ),
    ]
