# Generated by Django 2.2 on 2019-04-25 10:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('furnitures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(5)])),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileUser')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnitures.Furniture')),
            ],
        ),
    ]
