# Generated by Django 2.2 on 2019-04-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0004_auto_20190425_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='material',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='furnitures.Material'),
        ),
    ]
