# Generated by Django 2.2 on 2019-04-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0005_auto_20190426_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
